[package]

name = "synth"
description = "A polyphonic Synth type whose multiple oscillators generate sound via amplitude and frequency envelopes."
version = "0.0.2"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "README.md"
keywords = ["synthesis", "dsp", "audio", "music", "instrument"]
license = "MIT"
repository = "https://github.com/RustAudio/synth.git"
homepage = "https://github.com/RustAudio/synth"


[dependencies.dsp-chain]
git = "https://github.com/RustAudio/dsp-chain.git"

[dependencies]
envelope = "*"
mindtree_utils = "*"
pitch_calc = "*"
rand = "*"
rustc-serialize = "*"
simple_gaussian = "*"
time_calc = "*"

