[package]

name = "synth"
description = "A polyphonic Synth type whose multiple oscillators generate sound via amplitude and frequency envelopes."
version = "0.5.2"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "README.md"
keywords = ["synthesis", "dsp", "audio", "music", "instrument"]
license = "MIT"
repository = "https://github.com/RustAudio/synth.git"
homepage = "https://github.com/RustAudio/synth"


[dependencies]
dsp-chain = "*"
envelope = "*"
mindtree_utils = "*"
num = "*"
panning = "*"
pitch_calc = "*"
rand = "*"
rustc-serialize = "*"
simple_gaussian = "*"
time_calc = "*"

